### ISSUE TITLE
Microclimate UI not coming UP on IBM cloud private 3.1.0

### ISSUE THREAD

**Issue by arjunsbabu** [microclimate-dev2ops/microclimate-dev2ops.github.io#61]
We have installed microclimate 1.10 using helm chart in ICP catalog. Installation went fine. But the microclimate UI is not coming up. Its keep on loading.Please find the screenshot. I tryed restarting the pod. 

The pod is showing the below error 
`````
[Tue Apr 02 2019 03:28:59:548 UTC] [LOG]   portal/authentication/oidc.js: User admin has successfully authenticated.
[02/04/19 03:29:34 LoadRunner.js] [INFO] Loadrunner has connected
[Tue Apr 02 2019 03:29:43:891 UTC] [LOG]   DevOps Web Socket unexpected response
[Tue Apr 02 2019 03:29:43:891 UTC] [LOG]   Service unavailable - will retry
[Tue Apr 02 2019 03:29:43:892 UTC] [LOG]   DevOps Web Socket error
[Tue Apr 02 2019 03:29:43:892 UTC] [DIR]   Error: WebSocket was closed before the connection was established
    at WebSocket.close (/node_modules/ws/lib/websocket.js:206:14)
    at takeDownDevopsWebSocket (/devops.js:469:23)
    at WebSocket.devOpsWSUnexpected (/devops.js:422:11)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at ClientRequest.req.on (/node_modules/ws/lib/websocket.js:556:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
[Tue Apr 02 2019 03:29:43:892 UTC] [LOG]   DevOps Web Socket closed
[Tue Apr 02 2019 03:31:43:934 UTC] [LOG]   DevOps Web Socket unexpected response
[Tue Apr 02 2019 03:31:43:935 UTC] [LOG]   Service unavailable - will retry
[Tue Apr 02 2019 03:31:43:935 UTC] [LOG]   DevOps Web Socket error
[Tue Apr 02 2019 03:31:43:935 UTC] [DIR]   Error: WebSocket was closed before the connection was established
    at WebSocket.close (/node_modules/ws/lib/websocket.js:206:14)
    at takeDownDevopsWebSocket (/devops.js:469:23)
    at WebSocket.devOpsWSUnexpected (/devops.js:422:11)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at ClientRequest.req.on (/node_modules/ws/lib/websocket.js:556:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
[Tue Apr 02 2019 03:31:43:935 UTC] [LOG]   DevOps Web Socket closed
Collapse


`````

**Comment by arjunsbabu** [comment]
![microclimate](https://user-images.githubusercontent.com/29661675/55377422-83d4d500-5532-11e9-9668-9ce3f50c120e.JPG)

**Comment by sishida** [comment]
Thank you for bringing this issue to our attention. I see that this issue is being handled on a Slack channel, so I will go ahead and close it out here in GitHub. Thank you!
